# Generated by Django 4.1 on 2024-03-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='manual_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(choices=[('LIFE_FUNERAL', 'life_funeral'), ('CREDIT_LIFE', 'credit_life')], max_length=30),
        ),
    ]
