# Generated by Django 4.1 on 2024-02-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('entity_type', models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization')], max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('policy_terms', models.IntegerField(blank=True, null=True)),
                ('policy_number', models.CharField(blank=True, max_length=200, null=True)),
                ('policy_details', models.JSONField(blank=True, null=True)),
                ('policy_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('QUOTATION', 'Quotation')], max_length=20)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='policy_agent', to='policies.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_client_details', to='clients.clientdetails')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_insurance_company', to='config.insurancecompany')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyPaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_schedule_details', models.JSONField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_payment_schedule', to='policies.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_details', models.JSONField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('QUOTATION', 'Quotation')], max_length=20)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='')),
                ('payment_receipt_date', models.DateField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('policy_schedule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_schedule_premium_payments', to='policies.policypaymentschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('dependant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dependant_dob', models.DateField(blank=True, null=True)),
                ('dependant_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('dependant_address_street', models.CharField(blank=True, max_length=200, null=True)),
                ('dependant_address_suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('dependant_address_town', models.CharField(blank=True, max_length=200, null=True)),
                ('dependant_address_province', models.CharField(blank=True, max_length=200, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_dependants', to='policies.policy')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='relationship_dependant', to='config.relationships')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_dob', models.DateField(blank=True, null=True)),
                ('beneficiary_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20)),
                ('beneficiary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('beneficiary_address_street', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_address_suburb', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_address_town', models.CharField(blank=True, max_length=200, null=True)),
                ('beneficiary_address_province', models.CharField(blank=True, max_length=200, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_beneficiary', to='policies.policy')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='relationship_beneficiary', to='config.relationships')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
