# Generated by Django 4.1 on 2024-02-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='entity_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], max_length=20),
        ),
    ]
