# Generated by Django 4.1 on 2024-03-05 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_agent'),
        ('policies', '0002_alter_agent_entity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name': 'Beneficiary', 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterModelOptions(
            name='dependant',
            options={'verbose_name': 'Dependant', 'verbose_name_plural': 'Dependants'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policy', 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='policypaymentschedule',
            options={'verbose_name': 'Policy Payment Schedule', 'verbose_name_plural': 'Policy Payment Schedules'},
        ),
        migrations.AlterModelOptions(
            name='premiumpayment',
            options={'verbose_name': 'Premium Payment', 'verbose_name_plural': 'Premium Payments'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='policy_agent', to='config.agent'),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
