# Generated by Django 4.1 on 2024-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_beneficiary_options_alter_dependant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_status',
            field=models.CharField(choices=[('A', 'Active'), ('L', 'Lapsed'), ('X', 'Cancelled'), ('E', 'Expiry'), ('C', 'Claimed'), ('R', 'Reinstated'), ('N', 'Not Taken Up (Non payment of premium)'), ('P', 'Paid Up'), ('S', 'Surrendered'), ('SR', 'Surrendered due to replacement'), ('T', 'Transferred out')], max_length=20),
        ),
        migrations.AlterField(
            model_name='premiumpayment',
            name='payment_status',
            field=models.CharField(choices=[('A', 'Active'), ('L', 'Lapsed'), ('X', 'Cancelled'), ('E', 'Expiry'), ('C', 'Claimed'), ('R', 'Reinstated'), ('N', 'Not Taken Up (Non payment of premium)'), ('P', 'Paid Up'), ('S', 'Surrendered'), ('SR', 'Surrendered due to replacement'), ('T', 'Transferred out')], max_length=20),
        ),
    ]
