# Generated by Django 4.1 on 2024-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_policy_policy_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='premium',
            new_name='total_premium',
        ),
        migrations.AddField(
            model_name='policy',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='commission_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='external_reference',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='sum_insured',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
