# Generated by Django 4.1 on 2024-03-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_rename_premium_policy_total_premium_policy_admin_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='policy_terms',
            new_name='policy_term',
        ),
    ]
