# Generated by Django 4.1 on 2024-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_beneficiary_beneficiary_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='external_reference',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
