# Generated by Django 4.1 on 2024-03-15 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_alter_agent_entity_type'),
        ('policies', '0009_alter_beneficiary_beneficiary_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='policy_name_policy', to='config.policyname'),
        ),
    ]
