# Generated by Django 4.1 on 2024-03-17 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_policy_policy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpayment',
            name='policy_schedule',
        ),
        migrations.CreateModel(
            name='PremiumPaymentScheduleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_payment_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payment_links', to='policies.policypaymentschedule')),
                ('premium_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payment_links', to='policies.premiumpayment')),
            ],
        ),
    ]
