# Generated by Django 4.1 on 2024-03-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_remove_premiumpayment_policy_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumpayment',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='policy_premium_payment', to='policies.policy'),
            preserve_default=False,
        ),
    ]
