# Generated by Django 4.1 on 2024-03-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_premiumpayment_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpayment',
            name='payment_status',
        ),
    ]
