# Generated by Django 4.1 on 2024-03-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_remove_premiumpayment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpayment',
            name='payment_receipt_date',
        ),
    ]
