# Generated by Django 4.1 on 2024-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_remove_premiumpayment_payment_receipt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='policypaymentschedule',
            name='term',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
