# Generated by Django 4.1 on 2024-03-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0016_policy_business_unit_policy_premium_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='business_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='sum_insured',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
