# Generated by Django 4.1 on 2024-06-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0020_policy_submitted_to_insurer'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='entity',
            field=models.CharField(default='Nifty Cover', max_length=50),
        ),
    ]
