# Generated by Django 4.1 on 2024-06-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0021_policy_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('ifk_client_number', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('ifk_transaction_type', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=200, null=True)),
                ('minfo', models.CharField(blank=True, max_length=200, null=True)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cfk_branch', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='client_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='policy_payment_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='teller_transaction_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
