# Generated by Django 4.1 on 2024-07-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_alter_agent_entity_type'),
        ('policies', '0022_clicharge_premiumpayment_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='insurer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='policy_insurance_company', to='config.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_status',
            field=models.CharField(choices=[('A', 'Active'), ('L', 'Lapsed'), ('X', 'Cancelled'), ('E', 'Expiry'), ('C', 'Claimed'), ('R', 'Reinstated'), ('N', 'Not Taken Up (Non payment of premium)'), ('P', 'Paid Up'), ('F', 'Paid Up'), ('S', 'Surrendered'), ('SR', 'Surrendered due to replacement'), ('T', 'Transferred out')], max_length=20),
        ),
    ]
