# Generated by Django 4.1 on 2024-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0023_alter_policy_insurer_alter_policy_policy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
