# Generated by Django 4.1 on 2024-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0024_alter_policy_policy_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumpayment',
            name='branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
