# Generated by Django 4.1 on 2024-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0026_remove_policy_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_provider_type',
            field=models.CharField(default='Internal Credit Life', max_length=25),
        ),
    ]
