# Generated by Django 4.1 on 2024-07-25 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0027_policy_policy_provider_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='submitted_to_insurer',
        ),
    ]
