# Generated by Django 4.1 on 2024-07-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0028_remove_policy_submitted_to_insurer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='admin_fee',
        ),
    ]
