# Generated by Django 4.1 on 2024-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0029_remove_policy_admin_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='entity',
            field=models.CharField(default='Nifty Cover', max_length=50),
        ),
        migrations.AddField(
            model_name='policy',
            name='submitted_to_insurer',
            field=models.BooleanField(default=False),
        ),
    ]
