# Generated by Django 4.1 on 2024-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0030_policy_admin_fee_policy_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_provider_type',
            field=models.CharField(blank=True, default='Internal Credit Life', max_length=25, null=True),
        ),
    ]
