# Generated by Django 4.1 on 2024-07-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0031_alter_policy_policy_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_legacy',
            field=models.BooleanField(default=True),
        ),
    ]
