# Generated by Django 4.1 on 2024-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0032_policy_is_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='entity',
            field=models.CharField(default='Indlu', max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
    ]
