# Generated by Django 4.1 on 2024-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0034_policy_closed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
