# Generated by Django 4.1 on 2024-08-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0036_policy_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_warned_of_non_payment',
            field=models.BooleanField(default=False),
        ),
    ]
