# Generated by Django 4.1 on 2024-09-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0039_covercharges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covercharges',
            old_name='package',
            new_name='package_name',
        ),
    ]
