# Generated by Django 4.1 on 2024-10-15 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0040_rename_package_covercharges_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_beneficiary', to='policies.policy', unique=True),
        ),
        migrations.CreateModel(
            name='StatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('policy_status', models.CharField(choices=[('A', 'Active'), ('L', 'Lapsed'), ('X', 'Cancelled'), ('E', 'Expiry'), ('C', 'Claimed'), ('R', 'Reinstated'), ('N', 'Not Taken Up (Non payment of premium)'), ('P', 'Paid Up'), ('F', 'Paid Up'), ('S', 'Surrendered'), ('SR', 'Surrendered due to replacement'), ('T', 'Transferred out')], max_length=20)),
                ('status_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_snapshots', to='policies.policy')),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
    ]
