# Generated by Django 4.1 on 2024-10-16 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_remove_paymentaccount_account_number_and_more'),
        ('policies', '0041_alter_beneficiary_policy_statussnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='primary_id_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='beneficiary_id_document_type', to='config.iddocumenttype'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='primary_id_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dependant',
            name='primary_id_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='dependant_id_document_type', to='config.iddocumenttype'),
        ),
        migrations.AddField(
            model_name='dependant',
            name='primary_id_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
