# Generated by Django 4.1 on 2024-10-21 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0042_beneficiary_primary_id_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_beneficiary', to='policies.policy'),
        ),
    ]
