# Generated by Django 4.1 on 2024-10-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0043_alter_beneficiary_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumpayment',
            name='client_transaction_id',
        ),
        migrations.AddField(
            model_name='premiumpayment',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
