# Generated by Django 4.1 on 2024-11-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0045_remove_premiumpayment_policy_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='creation_stage',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('ON_ASSESSMENT', 'On Assessment'), ('REVIEW', 'Review'), ('DECLINED', 'Declined'), ('CREATED', 'Created')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='lock',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CreationStageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('creation_stage', models.CharField(choices=[('INITIATED', 'Initiated'), ('ON_ASSESSMENT', 'On Assessment'), ('REVIEW', 'Review'), ('DECLINED', 'Declined'), ('CREATED', 'Created')], default='INITIATED', max_length=20)),
                ('stage_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='creation_snapshots', to='policies.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_stage_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
    ]
