# Generated by Django 4.1 on 2024-02-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('claim_status', models.CharField(blank=True, max_length=200, null=True)),
                ('claimant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('claimant_surname', models.CharField(blank=True, max_length=200, null=True)),
                ('claimant_id_number', models.CharField(blank=True, max_length=200, null=True)),
                ('claimant_id_type', models.CharField(blank=True, max_length=200, null=True)),
                ('claimant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('claimant_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('claimant_bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('claimant_bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('claimant_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('claimant_branch_code', models.CharField(blank=True, max_length=50, null=True)),
                ('claim_assessed_by', models.CharField(blank=True, max_length=200, null=True)),
                ('claim_assessment_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claim_details', models.JSONField(blank=True, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('claim_paid_date', models.DateField(blank=True, null=True)),
                ('claim_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_type', to='config.claimtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=200, null=True)),
                ('document_file', models.FileField(upload_to='claims/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_document', to='claims.claim')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_document_type', to='config.documenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
