# Generated by Django 4.1 on 2024-03-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_policytypefields'),
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimant_id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='claimant_id_document_type', to='config.iddocumenttype'),
            preserve_default=False,
        ),
    ]
