# Generated by Django 4.1 on 2024-03-19 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_alter_policy_sum_insured'),
        ('claims', '0003_alter_claim_options_alter_claimdocument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='claim_policy', to='policies.policy'),
            preserve_default=False,
        ),
    ]
