# Generated by Django 4.1 on 2024-06-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claim_rejected_date_claim_rejected_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
