# Generated by Django 4.1 on 2024-07-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_claim_claim_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
