# Generated by Django 4.1 on 2024-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_claim_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='submitted_to_insurer',
            field=models.BooleanField(default=False),
        ),
    ]
