# Generated by Django 4.1 on 2024-07-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_claim_submitted_to_insurer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_rejected',
            new_name='claim_repudiated',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='rejected_date',
            new_name='repudiated_date',
        ),
        migrations.RenameField(
            model_name='claim',
            old_name='rejected_reason',
            new_name='repudiated_reason',
        ),
    ]
