# Generated by Django 4.1 on 2024-07-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_rename_claim_rejected_claim_claim_repudiated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ON_ASSESSMENT', 'On Assessment'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REPUDIATED', 'Repudiated')], default='CREATED', max_length=30),
        ),
    ]
