# Generated by Django 4.1 on 2024-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_alter_claim_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ON_ASSESSMENT', 'On Assessment'), ('SUBMITTED', 'Submitted'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('REPUDIATED', 'Repudiated')], default='CREATED', max_length=30),
        ),
    ]
