# Generated by Django 4.1 on 2024-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_alter_claim_claim_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type_id', models.IntegerField()),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notes', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FAILED', 'Failed'), ('SUCCESSFUL', 'Successful'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
    ]
