# Generated by Django 4.1 on 2024-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='check_number',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
