# Generated by Django 4.1 on 2024-09-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_remove_payment_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_type_id',
        ),
    ]
