# Generated by Django 4.1 on 2024-09-12 05:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0015_remove_payment_receipt_number_alter_payment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=5)),
                ('picked_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('assessment_date', models.DateTimeField(blank=True, null=True)),
                ('changes_made', models.TextField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='claims.claim')),
            ],
            options={
                'verbose_name': 'Claim Tracker',
                'verbose_name_plural': 'Claim Tracker',
            },
        ),
    ]
