# Generated by Django 4.1 on 2024-09-12 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_claimtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimdocument',
            name='actual_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='external_verification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='internally_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='old_doc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='trust_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimdocument',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ClientClaimDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='claim_client_documents', to='claims.claim')),
                ('client_documents', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='client_claim_documents', to='claims.claimdocument')),
            ],
            options={
                'verbose_name': 'Client Claim Document',
                'verbose_name_plural': 'Client Claim Documents',
            },
        ),
    ]
