# Generated by Django 4.1 on 2024-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0019_payment_payment_method_payment_receipt_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimdocument',
            name='document_file',
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
    ]
