# Generated by Django 4.1 on 2024-10-15 04:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_remove_claimdocument_document_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('claim_status', models.CharField(choices=[('CREATED', 'Created'), ('ON_ASSESSMENT', 'On Assessment'), ('SUBMITTED', 'Submitted'), ('REVIEW', 'Review'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REPUDIATED', 'Repudiated')], max_length=20)),
                ('status_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_snapshots', to='claims.claim')),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
    ]
