# Generated by Django 4.1 on 2024-03-03 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_businesssector_alter_iddocumenttype_options'),
        ('clients', '0003_alter_clientdetails_primary_id_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemploymentdetails',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_employment_business_sector', to='config.businesssector'),
        ),
    ]
