# Generated by Django 4.1 on 2024-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientdetails_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNKNOWN', 'Unknown')], max_length=20),
        ),
    ]
