# Generated by Django 4.1 on 2024-03-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_clientdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='address_street',
            field=models.TextField(blank=True, null=True),
        ),
    ]
