# Generated by Django 4.1 on 2024-03-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_clientdetails_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='primary_id_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
