# Generated by Django 4.1 on 2024-03-14 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clientdetails_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemploymentdetails',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_employment_details', to='clients.clientdetails'),
        ),
    ]
