# Generated by Django 4.1 on 2024-03-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_clientemploymentdetails_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=20),
        ),
    ]
