# Generated by Django 4.1 on 2024-03-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_alter_clientdetails_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='primary_id_number',
            field=models.CharField(max_length=200),
        ),
    ]
