# Generated by Django 4.1 on 2024-03-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_alter_clientdetails_external_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientemploymentdetails',
            options={'verbose_name': 'Client Employment Details', 'verbose_name_plural': 'Client Employment Details'},
        ),
    ]
