# Generated by Django 4.1 on 2024-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_clientdetails_client_details_clientdetails_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
