# Generated by Django 4.1 on 2024-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('type_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Loan Team',
                'verbose_name_plural': 'Loan Teams',
            },
        ),
        migrations.AlterModelOptions(
            name='claimfields',
            options={'verbose_name': 'Claim Field', 'verbose_name_plural': 'Claim Fields'},
        ),
        migrations.AlterModelOptions(
            name='claimtype',
            options={'verbose_name': 'Claim Type', 'verbose_name_plural': 'Claim Types'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Document Type', 'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterModelOptions(
            name='relationships',
            options={'verbose_name': 'Relationship', 'verbose_name_plural': 'Relationships'},
        ),
    ]
