# Generated by Django 4.1 on 2024-03-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_iddocumenttype_alter_claimfields_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sector', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Business Sector',
                'verbose_name_plural': 'Business Sectors',
            },
        ),
        migrations.AlterModelOptions(
            name='iddocumenttype',
            options={'verbose_name': 'ID Document Type', 'verbose_name_plural': 'ID Document Types'},
        ),
    ]
