# Generated by Django 4.1 on 2024-03-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_organisationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyTypeFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('input_type', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=False)),
                ('claim_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='policy_type_fields', to='config.policyname')),
            ],
            options={
                'verbose_name': 'Claim Field',
                'verbose_name_plural': 'Claim Fields',
            },
        ),
    ]
