# Generated by Django 4.1 on 2024-03-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_alter_policytypefields_options_claimfields_is_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policytypefields',
            old_name='claim_type',
            new_name='policy_type',
        ),
    ]
