# Generated by Django 4.1 on 2024-03-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_rename_claim_type_policytypefields_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyname',
            name='has_beneficiaries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policyname',
            name='has_dependencies',
            field=models.BooleanField(default=False),
        ),
    ]
