# Generated by Django 4.1 on 2024-03-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_policyname_has_beneficiaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyname',
            name='default_commission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
