# Generated by Django 4.1 on 2024-03-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_policyname_default_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='entity_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=20),
        ),
    ]
