# Generated by Django 4.1 on 2024-07-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_alter_businesssector_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_id', models.IntegerField()),
                ('division', models.CharField(max_length=15)),
                ('entity', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Loan Product Config',
                'verbose_name_plural': 'Loan Product Configs',
            },
        ),
    ]
