# Generated by Django 4.1 on 2024-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_loanproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanproduct',
            name='division',
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='business_unit',
            field=models.CharField(default='THF', max_length=40),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='is_legacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='policy_type_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='sub_scheme',
            field=models.CharField(default='Credit Life', max_length=40),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='entity',
            field=models.CharField(default='Indlu', max_length=60),
        ),
    ]
