# Generated by Django 4.1 on 2024-08-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_remove_loanproduct_division_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('payment_type_id', models.IntegerField()),
                ('account_number', models.CharField(max_length=60)),
                ('check_number', models.CharField(max_length=60)),
                ('routing_code', models.CharField(max_length=60)),
                ('bank_number', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=60, unique=True)),
                ('template_id', models.IntegerField()),
                ('service_name', models.TextField(blank=True, default=None, null=True)),
                ('sms_from', models.CharField(blank=True, max_length=500, null=True)),
                ('linked_organization', models.CharField(max_length=20)),
            ],
        ),
    ]
