# Generated by Django 4.1 on 2024-09-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_paymentaccount_sms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='bank_number',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='check_number',
        ),
        migrations.RemoveField(
            model_name='paymentaccount',
            name='routing_code',
        ),
    ]
