# Generated by Django 4.1 on 2024-11-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_remove_paymentaccount_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimantdetails',
            name='branch',
        ),
    ]
