# Generated by Django 4.1 on 2024-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_remove_claimantdetails_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimantdetails',
            name='currency',
            field=models.CharField(default='ZAR', max_length=10),
        ),
    ]
