# Generated by Django 4.1 on 2024-09-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audittrail_changes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditTrail',
        ),
    ]
