# Generated by Django 4.1 on 2024-03-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GUARDRISK', 'Guardrisk')], max_length=20)),
                ('access_key', models.CharField(blank=True, max_length=100, null=True)),
                ('base_url', models.URLField()),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Integration Config',
                'verbose_name_plural': 'Integration Configs',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.JSONField()),
                ('response_data', models.JSONField(null=True)),
                ('response_status', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(choices=[('GUARDRISK', 'Guardrisk')], max_length=20)),
            ],
            options={
                'verbose_name': 'Integration Request',
                'verbose_name_plural': 'Integration Requests',
            },
        ),
    ]
