# Generated by Django 4.1 on 2024-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfigs',
            name='entity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
