# Generated by Django 4.1 on 2024-06-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integrationconfigs_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconfigs',
            name='client_identifier',
            field=models.CharField(default='143', max_length=100),
        ),
    ]
